Feat/45 offices card
SAMAHAN-Systems-Development/samahan-all-for-more-frontend pull request #65
Opened 2024-10-14 14:14 UTC by arabellamejorada

read me pls:

- finished the structure of the office cards, but I need suggestions from u bossings on how to polish the bottom part of the component (sa cutout part) cause it looks like this and idk what to do na huhu:
<img width="403" alt="image" src="https://github.com/user-attachments/assets/26e727b4-eca9-4a2a-b8e4-026695a6c55e">

- also placed the View Office button below the name and position cause if I place it at the bottom right, it will ruin the structure of the image cutout. open for suggestions for this too!

(ps. a bit challenging ticket frfr. would love to hear from ur pr reviews po)

2024-10-16 11:03 UTC, shunindesuuu commented
hello ara! here are my suggestions lang

for the image:
- i think this is an issue sa cutout? so i guess pwede siguro edit ang image na naga overlap sa bottom left

for the button:
- try changing the z-index para di sila in the same layer with the image

2024-10-16 11:16 UTC, shunindesuuu commented on src/components/office-cards/BaseCard.tsx
> +    <div className="relative flex items-center bg-blue text-white w-full max-w-[900px] rounded-[30px] md:max-w-[900px] transition-all duration-300 overflow-visible" style={{ height: '400px' }}>
change this to tailwind

2024-10-16 11:16 UTC, shunindesuuu commented on src/components/office-cards/BaseCard.tsx
> +      <div className="absolute left-0 bottom-0 w-[50%] h-auto" style={{ transform: 'translateY(-.1%)' }}>
this one as well

2024-10-18 02:04 UTC, miggyalino requested changes
Please delete OSG, OSP, OST, OVP Card component. No need na since ang difference lang kay ang props being passed in. Ipa pass in lang ni sa mag gamit sa component.

2024-10-18 09:44 UTC, shunindesuuu approved these changes

2024-10-18 10:18 UTC, miggyalino approved these changes

2024-10-18 10:39 UTC, merged